ALTER TABLE Cliente
    ADD COLUMN cidade VARCHAR(100),
    ADD COLUMN codigo INTEGER UNIQUE;

ALTER TABLE Produto
    ADD COLUMN codigo INTEGER UNIQUE;

ALTER TABLE Usuario
    ADD COLUMN codigo INTEGER UNIQUE;

ALTER TABLE Aluguel
    ADD COLUMN codigo INTEGER UNIQUE;

ALTER TABLE Categoria
    ADD COLUMN codigo INTEGER UNIQUE;

ALTER TABLE Funcionario
    ADD COLUMN codigo INTEGER UNIQUE;
